### ISSUE TITLE
netstat is discouraged in modern Linux; try ss first in Linux

### ISSUE THREAD

**Issue by tats-u** [google/cdc-file-transfer#65]
In RHEL 7+ and Ubuntu 17.04+, `netstat` is deprecated and not installed by default.
This program works in Alma 9 only after running ```sudo ln -s `which ss` /usr/local/bin/netstat```.
The option and output of `ss` is so similar to `netstat` that this program can use it as an alternative to `netstat`.

**Comment by ljusten** [comment]
Nice, thanks, ss is even faster than netstat. You can also set --forward-port=<some available port> to skip the port detection altogether. That's actually a bit faster as well.

I'd like to get rid of the whole netstat calling logic and detect the ports in the remote components (e.g. cdc_rsync_server) in code, but that'll require some bigger refactorings since right now cdc_rsync_server and port forwarding are started at the same time.

**Comment by ljusten** [comment]
I'll replace the netstat command by
```
if which ss; then ss --numeric --listening --tcp; else netstat --numeric --listening --tcp; fi
```

**Comment by tats-u** [comment]
@ljusten `remote_util->BuildProcessStartInfoForSsh` can handle shell scripts, right?

https://github.com/google/cdc-file-transfer/blob/d8c2b5906eac260624010f4b9697843236c174b4/common/port_manager_win.cc#L235-L283

The candidate you have just show me may not work if the remote shell is fish or other shells incompatible with sh.

**Comment by ljusten** [comment]
That's true, but we already run similar code elsewhere, so at least it doesn't make the problem more severe. The real solution is to get rid of all shell scripts, but that's much more work.

https://github.com/google/cdc-file-transfer/blob/d8c2b5906eac260624010f4b9697843236c174b4/cdc_rsync/cdc_rsync_client.cc#L210

**Comment by ljusten** [comment]
Actually, this should work in a wider range of (all?) shells:
```
which ss && ss --numeric --listening --tcp || netstat --numeric --listening --tcp
```
It also has the advantage that it falls back to netstat if executing ss fails.

**Comment by tats-u** [comment]
@ljusten It has more portability. Does the `ss`'s path vomited by `which` occur unintended behavior?

```
$ which git && echo aaa || echo bbb
/usr/bin/git
aaa
$ which foo && echo aaa || echo bbb
bbb
```

**Comment by ljusten** [comment]
Yes, it's ignored when analyzed. It can be hidden by adding `> /dev/null` after `which ss`, but I think it's a useful thing to have in debug logs since this way we know which one was executed.

**Comment by tats-u** [comment]
@ljusten I got it. I'll leave it to you. Thank you for your quick response.

**Comment by tats-u** [comment]
I found missing netstat is treated as the connection timeout without -vvv.
This causes users' misunderstanding.

**Comment by tats-u** [comment]
@ljusten Thank you for the fix!
