### ISSUE TITLE
Patching of file isn't working

### ISSUE THREAD

**Issue by azvenigo** [google/cdc-file-transfer#82]
I'm testing the behavior when a file hasn't changed by size or date but I'd still like to be able to break it up by CDC and patch. (Using the -c checksum flag to ensure it breaks the file up by chunks and look for existing chunks on the server.)

What I'm finding is that, even though a file hasn't changed, it's not finding any matching chunks on the server and ends up transmitting the entire file still.

It's clearly returning the right number of offsets and hashes from the server. But in TryAddChunks() where it searches for matching chunk.hash it's always coming back false. 

This is with syncing a file that was just sync'd on the previous run. 

Wondering if I'm doing something wrong or if there's some way the hashing algorithm differs between client (Windows 10, Intel Xeon) and server (Ubuntu, Threadripper)  I was planning on verifying that next but wanted to ask whether you've seen this before.

Thanks

**Comment by ljusten** [comment]
Odd, I've never seen that. If the server chunks have not been fully transmitted, it is possible that the `chunk.hash` is not found until the server catches up sending the data. In that case, the patcher will just try again later until `server_chunk_receiver.AllChunksReceived()` is true. Is the `chunk.hash` not found even after `server_chunk_receiver.AllChunksReceived()` becomes true?

Is this reproducible with a very small file (<1KB)? In that case, there should only be one chunk, and it should be easy to check what's going on. It could be 3 things: The chunkers/hashers on the client and server get different input data (should not be the case as the files are the same), they produce different outcomes (should not be the case as both chunker and hasher should be deterministic) or something else is wrong and the hash doesn't get transmitted properly. 

Also, what version are you on? 1.0.0 or latest? If you're on latest, does it repro in 1.0.0?

**Comment by azvenigo** [comment]
Hi Lutz,

I'm on the latest in the main branch. Interestingly with a single chunk, (4kib file) it does compute the same hash and sees that it exists. I added a bit of logging:
```
client index:0 hash:0xbebbe3943b26b03cca080877ee363ed7
server index:0 offset:0 hash:0xbebbe3943b26b03cca080877ee363ed7
exist:1 new:0
```

With an 8kib test file, however the hashes don't match. Current theory is it's finding different breakpoints for some strange reason:
```
client index:0 hash:0x5038485c6b212bac1ca6d317030fc861
client index:1 hash:0xffb716ec699ed51f78b265ae24cb07c0
server index:0 offset:0x0 hash:0xed43e104e14bef74aba332fd3f1297e
server index:1 offset:0x1e10 hash:0xa25e0802b7476c8b450d906c012c420e
exist:0 new:1
exist:0 new:1
```

(TryAddChunks is being called twice which is why it's reporting exists vs new twice. )
I've verified that the full file SHA256 is the same between client and server, so it's got to be something else. I'm going to see if I can determine the FastCDC breakpoint to verify that's identical.

**Comment by ljusten** [comment]
Yeah I was about to suggest that. We made a tiny change to fastcdc.h, which would perfectly explain those symptoms.
